### ISSUE TITLE
Support Security Contexts for GID, UID, and fsGroup in OpenShift

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#1152]
**what do you want**
Be able to support arbitrary Security Contexts for GID, UID, and fsGroup in OpenShift.

BlackDuck Ticket: https://jira.dc1.lan/browse/HUB-20580

**why is this needed**
PodSecurityPolicies can prevent Pods from running if the Security Contexts are not set. 
Similarly, SecurityContextConstraints in Openshift can prevent Pods from running.

**TODO**
- [ ] Add a flag to Synopsysctl to set SecurityContext constraints
- [ ] Modify synopsysctl to create a service account for all resources if on Kubernetes/Openshift (this will make it easy for customers to add the Product to a SecurityContextConstraint)
- [ ] Verify the BlackDuck images can run without being root (aka GID, UID, and fsGroup are not 0)
- [ ] Verify Pods can run with a PodSecurityPolicy enabled
- [ ] Verify Pods can run with a SecurityContextConstraint enabled
- [ ] Test in Openshift

**example implementation**
https://github.com/blackducksoftware/polaris-contrib/tree/master/blackduck-synopsysctl-example-GID1000
