### ISSUE TITLE
Support arbitrary Security Contexts for GID, UID, and fsGroup for Kubernetes

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/synopsys-operator#936]
**what do you want**
Be able to support arbitrary Security Contexts for GID, UID, and fsGroup for Kubernetes.

BlackDuck Ticket: https://jira.dc1.lan/browse/HUB-20580

**why is this needed**
PodSecurityPolicies can prevent Pods from running if the Security Contexts are not set. 
Similarly, SecurityContextConstraints in Openshift can prevent Pods from running.

**TODO**
- [x] Add a flag to Synopsysctl to set SecurityContext constraints
- [x] Modify synopsysctl to create a service account for all resources if on Kubernetes/Openshift (this will make it easy for customers to add the Product to a SecurityContextConstraint)
- [x] Verify the BlackDuck images can run without being root (aka GID, UID, and fsGroup are not 0)
- [x] Verify Pods can run with a PodSecurityPolicy enabled
- [x] Verify Pods can run with a SecurityContextConstraint enabled
- [x] Test in onprem Kubernetes
- [x] Test in GKE

**example implementation**
https://github.com/blackducksoftware/polaris-contrib/tree/master/blackduck-synopsysctl-example-GID1000

**Comment by yashbhutwala** [comment]
new xref: https://jira-sig.internal.synopsys.com/browse/HUB-20580

**Comment by yashbhutwala** [comment]
Upon @jdartigalongue recommendation, specifically will only be adding a `--fsGroup` flag, and will have two versions of postgres (one for kubernetes, with UID 26 [due to GKE] and one for Openshift, with no uid)

**Comment by yashbhutwala** [comment]
depends on #972

**Comment by mphammer** [comment]
Test on GKE, DC1, K8s, and Openshift
